#! /bin/sh

## Autostart Programs
sxhkd &
# polybar example &
#~/.scripts/panel.sh
killall polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar mainbar &
#MONITOR=DP-5 polybar example &
~/.fehbg
picom -b --experimental-backends
lxsession &
blueman-applet &
nm-applet &

## Configure Monitors/Workspaces
bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9
bspc monitor DP-5 -d 1 2 3 4 5 6 7 8 9

## Theming
bspc config border_width        0
bspc config window_gap          12
bspc config top_padding         20
bspc config left_padding        0
bspc config right_padding       0
bspc config bottom_padding      0
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

# Colors
bspc config normal_border_color     "#4C566A"
bspc config active_border_color     "#81A1C1"
bspc config focused_border_color    "#D8DEE9"
bspc config presel_feedback_color   "#5E81AC"
bspc config urgent_border_color     "#BF616A"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled

# Polybar Hidden When Fullscreen for Vlc, Youtube, Mpv ...
xdo below -t $(xdo id -n root) $(xdo id -a polybar-mainbar_DP-2)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-2)

## Make Focus Follow Cursor
bspc config focus_follows_pointer true
