#! /bin/sh

## Autostart Programs
sxhkd &
# polybar example &
#~/.scripts/panel.sh
if [ $(pgrep polybar) ]; then
	killall -q polybar && sleep .5 && polybar mainbar &
else
	sleep .5 && polybar mainbar &
fi
#MONITOR=DP-5 polybar example &
~/.fehbg
picom &
if [ $(pgrep ibus-daemon) ]; then
	killall -q ibus-daemon && ibus-daemon -drxR &
else
	ibus-daemon -drxR &
fi
lxsession &
blueman-applet &
nm-applet &

## Configure Monitors/Workspaces
bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9
bspc monitor DP-3 -d 1 2 3 4 5 6 7 8 9

## Theming
bspc config border_width        4
bspc config window_gap          40
bspc config top_padding         20
bspc config left_padding        0
bspc config right_padding       0
bspc config bottom_padding      0
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config ignore_ewmh_fullscreen all

# Colors
bspc config normal_border_color     "#928374"
bspc config focused_border_color    "#D79921"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled

# Polybar Hidden When Fullscreen for Vlc, Youtube, Mpv ...
xdo below -t $(xdo id -n root) $(xdo id -a polybar-mainbar_DP-0)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main)

## Make Focus Follow Cursor
bspc config focus_follows_pointer true
