#! /bin/sh

## Autostart Programs
sxhkd &
# polybar example &
~/.scripts/panel.sh
~/.fehbg
picom -b
nm-applet &
killall pasystray
killall udiskie
pasystray &
dunst &
udiskie --tray &

## Configure Monitors/Workspaces
bspc monitor HDMI-0 -d Web Term School Game Music Chat Sys Dev Extra
bspc monitor DP-3 -d Web Term School Game Music Chat Sys Dev Extra

## Theming
bspc config border_width        1
bspc config window_gap          0
bspc config top_padding         20
bspc config left_padding        0
bspc config right_padding       0
bspc config bottom_padding      0
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

# Colors
bspc config normal_border_color     "#c678dd"
bspc config active_border_color     "#c678dd"
bspc config focused_border_color    "#98c379"
bspc config presel_feedback_color   "#61afef"
bspc config urgent_border_color     "#e06c75"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Polybar Hidden When Fullscreen for Vlc, Youtube, Mpv ...
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-3)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-0)

## Make Focus Follow Cursor
bspc config focus_follows_pointer true
